/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 97a18e6faa0a575db6e5e776d7f613f1)
interface __BaseEnv_Env {
	BriefAgent: DurableObjectNamespace<import("./src/server/index").BriefAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "BriefAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}