/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7f38a9ac8f6ad8cf128baf9363179a65)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	EMAIL_FROM: "brief@designhouse.me";
	ALLOWED_EMAIL_DOMAINS: "designhouse.me";
	BriefAgent: DurableObjectNamespace<import("./src/server/index").BriefAgent>;
	Accounts: DurableObjectNamespace<import("./src/server/index").AccountStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "BriefAgent" | "AccountStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "ALLOWED_EMAIL_DOMAINS">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}